### ISSUE TITLE
[Chore] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by pcsoyeon** [Team-Beforeget/Beforeget-iOS#1]
## 💡 Issue
프로젝트 초기 설정

## 📝  todo
- [x] 폴더링
- [x] 컬러 에셋 추가
- [x] 폰트 에셋 추가 
- [x] SPM, Podfile 추가
