### ISSUE TITLE
[Feat] 기록뷰 기능 로직 구현

### ISSUE THREAD

**Issue by heerucan** [Team-Beforeget/Beforeget-iOS#19]
## 💡 Issue
기록뷰 기능 로직 구현합니다.

## 📝  todo
- [x] 필터 선택 활성화 관련
- [x] 필터 선택 시에 데이터 전달 -> 필터뷰 메뉴로
- [x] 초기화 버튼 대응
