### ISSUE TITLE
[Feat] 화면 전체 Flow 연결

### ISSUE THREAD

**Issue by heerucan** [Team-Beforeget/Beforeget-iOS#31]
## 💡 Issue
전체 View Flow 연결

## 📝  todo
- [x] 화면 전체 플로우 연결합니다.
- [x] 흐름에 부족한 부분 구현
- [ ] 글쓰기 완료 화면 구현
- [x] 팝업 연결
