### ISSUE TITLE
[Feat] 통계 서버 연결 

### ISSUE THREAD

**Issue by pcsoyeon** [Team-Beforeget/Beforeget-iOS#43]
## 💡 Issue
통계뷰 서버 연결을 구현합니다.

## 📝  todo
- [x] 특정달 통계 데이터 받기 
- [x] 월별 추이 데이터 받기
- [x] Top3 데이터 받기
- [x] 한줄평 데이터 받기
- [x] 전체 모아보기 데이터 받기 
- [ ] 뷰와 연결
