### ISSUE TITLE
[Hotfix] 나의 기록 상세조회, 전체글보기 UI 및 로직 오류 수정

### ISSUE THREAD

**Issue by heerucan** [Team-Beforeget/Beforeget-iOS#59]
## 💡 Issue

나의 기록 상세조회, 전체글보기 UI 및 로직 오류 수정

## 📝  todo
- [ ] 나의 기록 상세조회 레이아웃 수정
- [ ] 나의 제목 2줄 습할
- [ ] 날짜 형식
- [ ] 장르 형식
- [ ] 장르에 들어오는 데이터
- [ ] 노래에 들어오는 데이터
- [ ] 필터 처리한 다음에 넘어가는 화면
